include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: true
  exclude:
    # Generated serverpod files.
    - packages/pub_quiz_client/lib/src/protocol/*
    - packages/pub_quiz_server/lib/src/generated/*
    - packages/pub_quiz_server/test/integration/test_tools/serverpod_test_tools.dart

linter:
  rules:
    - avoid_positional_boolean_parameters
    - prefer_const_declarations
    - prefer_final_in_for_each
    - prefer_final_locals
